### ISSUE TITLE
[Feature Request] Spawn other items as well

### ISSUE THREAD

**Issue by Al12rs** [ItsBranK/BakkesBanners#1]
Hi, thank you for the plugin!
I wanted to ask if it was possible to spawn in other items, such as boosts, explosions etc as well.
I read on your Twitter that you tried this for the Anthems but the music sounded messed up.
Are there similar problems with the other items types as well? Or is the reasoning simply that baskkesmod already allows equipping the other items?

I think your approach with spawning in the items is much more appealing since you can actually see them before equipping them, and when you have all the items in the game that is kind of a useful thing.

I read a bit the code and it looked like it should be possible and I was curious to know if you had already tested this and what kind of problems you encountered if yes.

**Comment by ItsBranK** [comment]
Banners and borders are the only ones that show up for the player, and not others. Spawning in other items just don't work at all, using online they get replaced with default items.

**Comment by Al12rs** [comment]
Ok thanks for the answer!
